version: 1
disable_existing_loggers: True

formatters:
    default:
        format: '%(asctime)s %(levelname)s [%(name)s:%(lineno)d] %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    file:
        class: logging.FileHandler
        level: NOTSET
        formatter: default
        filename: 'example.log'  # Output file path
        encoding: utf-8
        mode: w  # 'w' to overwrite each time, 'a' to append

    CLP_file:
        class: application.logger.RotatingCLPFileHandler
        level: NOTSET
        formatter: default
        filename_prefix: 'ictrl_'
        log_dir: 'logs'
        max_bytes: 8192  # Rotate after 8 KB
        backup_count: 10  # Keep 10 backup files
        enable_compression: True
        timestamp_format: '%Y-%m-%d_%H-%M-%S'

root:
    level: NOTSET
    handlers: [file, CLP_file]
